#!/usr/bin/env bash
# Serve vLLM on this node's GPUs, running the binary inside the CUDA vLLM sif.
# Reused by scripts/eval/run.sbatch (which backgrounds this and waits on /health).
# Foreground-exec model: this script runs vllm in the FOREGROUND; the caller is
# responsible for backgrounding it (run.sbatch does `bash serve_vllm.sh &`) and for
# stopping it.
#
# Usage (from the repo root):
#   VLLM_CUDA_SIF=/path/vllm.sif MODEL=Qwen/Qwen3.5-9B PORT=8000 \
#       bash scripts/serve/serve_vllm.sh
#
# Knobs (env vars) -- node/accelerator knobs only:
#   VLLM_CUDA_SIF    CUDA vLLM Singularity image (default $PWD/vllm-openai-cuda-*.sif
#                    is NOT assumed; set it, or SIF_PATH for a named base).
#   SIF_PATH         alias for VLLM_CUDA_SIF (legacy).
#   MODEL            HF repo to serve (default Qwen/Qwen3.5-9B).
#   PORT             serve port (default 8000).
#   TENSOR_PARALLEL  TP (default 1); DATA_PARALLEL DP (default 8).
#   MAX_MODEL_LEN    context length (default 262144).
#   GPU_MEM_UTIL     gpu-memory-utilization (default 0.85).
#   BASE_DIR         node-local base for scratch (default ${PBS_LOCALDIR:-${TMPDIR:-/tmp}}).
#   CACHE_DIR        single host cache dir bound at /cache (default
#                    ${XDG_CACHE_HOME:-${BASE_DIR}}/.cache -- honors the .env XDG_CACHE_HOME).
#   VLLM_ARGS_EXTRA  model-intrinsic vLLM flags (parsers, dtype, context knobs). These
#                    come from configs/serve/<MODEL>.json via run.sbatch; set explicitly
#                    for manual/standalone runs.
#   APPTAINER_BIN    override the container tool (auto: apptainer > singularity).
#   USE_RELAY=1      additionally expose the local vLLM through the Modal reverse
#                    relay (src/relay); requires RELAY_WS_URL + RELAY_SECRET (from
#                    `modal deploy src/relay/modal_relay.py`). Default 0 = serve
#                    locally only (run.sbatch polls /health directly).
#   RELAY_WS_URL     wss://<ws>--<app>-web.modal.run/bridge  (when USE_RELAY=1).
#   RELAY_SECRET     shared secret (matches the Modal relay secret).
#   VLLM_LOCAL_URL   local vLLM base for the bridge (default http://127.0.0.1:$PORT).
set -euo pipefail
# Under PBS/SLURM, $0 is the spooled script copy, so resolve the repo root via the
# submit dirs first (same as scripts/eval/run.sbatch), else the script's own path.
REPO_ROOT="${REPO_ROOT:-${PBS_O_WORKDIR:-${SLURM_SUBMIT_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}}}"
cd "$REPO_ROOT"

# PBS spools stdout on the exec node and only copies back at job end; tee to a
# shared-FS file so the live serve/bridge output is visible in logs/ (like
# scripts/eval/run.sbatch). Target mirrors PBS's own name: <jobname>.pbs1.out.
if [ -n "${PBS_JOBID:-}" ] && [ -n "${PBS_JOBNAME:-}" ] && [ -z "${SLURM_JOB_ID:-}" ]; then
    mkdir -p logs
    exec > >(tee -a "logs/${PBS_JOBNAME}.pbs1.out") 2>&1
    echo "[serve] teeing output to logs/${PBS_JOBNAME}.pbs1.out"
fi

VLLM_CUDA_SIF="${VLLM_CUDA_SIF:-${SIF_PATH:-}}"
MODEL="${MODEL:-Qwen/Qwen3.5-9B}"
PORT="${PORT:-8000}"
TENSOR_PARALLEL="${TENSOR_PARALLEL:-1}"
DATA_PARALLEL="${DATA_PARALLEL:-8}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-262144}"
GPU_MEM_UTIL="${GPU_MEM_UTIL:-0.85}"
BASE_DIR="${BASE_DIR:-${PBS_LOCALDIR:-${TMPDIR:-/tmp}}}"
# Honor the .env XDG_CACHE_HOME (node-local scratch) as the cache root; fall back to
# BASE_DIR (or /tmp) when unset (e.g. a login shell). Keeps caches off quota-limited HOME.
CACHE_DIR="${CACHE_DIR:-${XDG_CACHE_HOME:-${BASE_DIR}}/.cache}"
APPTAINER_BIN="${APPTAINER_BIN:-$(command -v apptainer || command -v singularity || echo singularity)}"
# Modal reverse-relay: when USE_RELAY=1, serve is exposed through src/relay/bridge.py
# (dials OUT to the relay; the node needs no inbound). The relay URL is generated by
# `modal deploy src/relay/modal_relay.py` once; pass RELAY_WS_URL + RELAY_SECRET.
USE_RELAY="${USE_RELAY:-0}"
RELAY_WS_URL="${RELAY_WS_URL:-}"
RELAY_SECRET="${RELAY_SECRET:-}"
VLLM_LOCAL_URL="${VLLM_LOCAL_URL:-http://127.0.0.1:${PORT}}"

if [ -z "${VLLM_CUDA_SIF}" ]; then
    echo "ERROR: VLLM_CUDA_SIF (or SIF_PATH) not set." >&2
    echo "       Build one first: scripts/build/build_vllm.sh cuda" >&2
    exit 2
fi
[ -f "${VLLM_CUDA_SIF}" ] || { echo "ERROR: sif not found: ${VLLM_CUDA_SIF}" >&2; exit 2; }
command -v "${APPTAINER_BIN}" >/dev/null 2>&1 || { echo "ERROR: container tool not found: ${APPTAINER_BIN}" >&2; exit 127; }

# ABCI/PBS can hand GPUs as UUIDs; vLLM needs integer indices.
case "${CUDA_VISIBLE_DEVICES:-}" in
    *[!0-9,]*)
        _NGPU=$(printf '%s' "${CUDA_VISIBLE_DEVICES}" | tr ',' '\n' | grep -c .)
        export CUDA_VISIBLE_DEVICES="$(seq -s, 0 $((_NGPU - 1)))"
        echo "[serve] normalized CUDA_VISIBLE_DEVICES -> ${CUDA_VISIBLE_DEVICES}" >&2 ;;
esac

echo "[serve] launching vLLM ${MODEL} :${PORT} (TP=${TENSOR_PARALLEL} DP=${DATA_PARALLEL}) in ${VLLM_CUDA_SIF}" >&2
mkdir -p "${CACHE_DIR}"
export APPTAINER_TMPDIR="${BASE_DIR}" SINGULARITY_TMPDIR="${BASE_DIR}"
# One host cache dir (node-local scratch, not quota-limited HOME) bound at /cache; all
# of HF models, vLLM's torch_compile_cache, and tmp live under it so nothing touches HOME.
vllm_argv=(
    "${APPTAINER_BIN}" exec --nv --writable-tmpfs
    --workdir "${BASE_DIR}"
    --bind "${CACHE_DIR}:/cache"
    --env TMPDIR=/cache/tmp
    --env HF_HOME=/cache/huggingface
    --env VLLM_CACHE_ROOT=/cache/vllm
    --env "CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-}"
    "${VLLM_CUDA_SIF}"
    vllm serve "${MODEL}"
        --host 0.0.0.0
        --port "${PORT}"
        --tensor-parallel-size "${TENSOR_PARALLEL}"
        --data-parallel-size "${DATA_PARALLEL}"
        --max-model-len "${MAX_MODEL_LEN}"
        --gpu-memory-utilization "${GPU_MEM_UTIL}"
)
# shellcheck disable=SC2206   # VLLM_ARGS_EXTRA is deliberately word-split into flags.
vllm_argv+=( ${VLLM_ARGS_EXTRA:-} )

if [ "${USE_RELAY}" = "1" ]; then
    [ -f "${REPO_ROOT}/src/relay/bridge.py" ] || { echo "ERROR: ${REPO_ROOT}/src/relay/bridge.py missing" >&2; exit 2; }
    # --- Step 1 (once per account): deploy the Modal relay if no URL was passed.
    # The Modal app exposes a stable auto-generated https://<ws>--<app>-web.modal.run
    # endpoint; the relay is reachable from Modal sandboxes and bridges to this node.
    if [ -z "${RELAY_WS_URL}" ]; then
        RELAY_APP_NAME="${RELAY_APP_NAME:-mho-vllm-relay}"
        RELAY_SECRET_NAME="${RELAY_SECRET_NAME:-mho-relay}"
        if [ -z "${RELAY_SECRET}" ]; then
            RELAY_SECRET="$(openssl rand -hex 16)"
            echo "[serve] creating/updating Modal secret ${RELAY_SECRET_NAME} (--force)" >&2
            uv run modal secret create --force "${RELAY_SECRET_NAME}" RELAY_SECRET="${RELAY_SECRET}" >&2                 || { echo "ERROR: \`uv run modal secret create\` failed (Modal auth?)." >&2; exit 2; }
        fi
        echo "[serve] deploying Modal relay app ${RELAY_APP_NAME}" >&2
        _DEPLOY_OUT="$(RELAY_APP_NAME="${RELAY_APP_NAME}" RELAY_SECRET_NAME="${RELAY_SECRET_NAME}"             uv run modal deploy src/relay/modal_relay.py 2>&1)"             || { echo "ERROR: relay deploy failed:" >&2; echo "${_DEPLOY_OUT}" >&2; exit 2; }
        echo "${_DEPLOY_OUT}" >&2
        _RELAY_URL="$(printf '%s' "${_DEPLOY_OUT}" | grep -oE 'https://[a-zA-Z0-9._-]+\.modal\.run' | head -1)"
        [ -n "${_RELAY_URL}" ] || { echo "ERROR: could not parse relay URL from deploy output" >&2; exit 2; }
        # The bridge WebSocket lives at wss:// (not https://) on the Modal app.
        RELAY_WS_URL="$(printf '%s' "${_RELAY_URL%/}" | sed "s#^https://#wss://#")/bridge"
        echo "[serve] relay deployed -> ${_RELAY_URL} ; bridge ws -> ${RELAY_WS_URL}" >&2
    fi
    echo "[serve] starting vLLM in background, then Modal relay bridge -> ${RELAY_WS_URL}" >&2
    "${vllm_argv[@]}" &
    VLLM_PID=$!
    trap 'kill "${VLLM_PID}" 2>/dev/null || true' EXIT TERM INT
    # Keep this script alive in the foreground holding the relay WebSocket open; the
    # node dials out (no inbound needed) and proxies requests to the local vLLM.
    (cd "${REPO_ROOT}" \
        && RELAY_WS_URL="${RELAY_WS_URL}" RELAY_SECRET="${RELAY_SECRET}" \
            VLLM_LOCAL_URL="${VLLM_LOCAL_URL}" \
            uv run --with websockets --with httpx python src/relay/bridge.py)
else
    exec "${vllm_argv[@]}"
fi